// Generated by gencpp from file depthai_ros_msgs/FFMPEGPacket.msg
// DO NOT EDIT!


#ifndef DEPTHAI_ROS_MSGS_MESSAGE_FFMPEGPACKET_H
#define DEPTHAI_ROS_MSGS_MESSAGE_FFMPEGPACKET_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace depthai_ros_msgs
{
template <class ContainerAllocator>
struct FFMPEGPacket_
{
  typedef FFMPEGPacket_<ContainerAllocator> Type;

  FFMPEGPacket_()
    : header()
    , width(0)
    , height(0)
    , encoding()
    , pts(0)
    , flags(0)
    , is_bigendian(false)
    , data()  {
    }
  FFMPEGPacket_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , width(0)
    , height(0)
    , encoding(_alloc)
    , pts(0)
    , flags(0)
    , is_bigendian(false)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _width_type;
  _width_type width;

   typedef int32_t _height_type;
  _height_type height;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _encoding_type;
  _encoding_type encoding;

   typedef uint64_t _pts_type;
  _pts_type pts;

   typedef uint8_t _flags_type;
  _flags_type flags;

   typedef uint8_t _is_bigendian_type;
  _is_bigendian_type is_bigendian;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::depthai_ros_msgs::FFMPEGPacket_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::depthai_ros_msgs::FFMPEGPacket_<ContainerAllocator> const> ConstPtr;

}; // struct FFMPEGPacket_

typedef ::depthai_ros_msgs::FFMPEGPacket_<std::allocator<void> > FFMPEGPacket;

typedef boost::shared_ptr< ::depthai_ros_msgs::FFMPEGPacket > FFMPEGPacketPtr;
typedef boost::shared_ptr< ::depthai_ros_msgs::FFMPEGPacket const> FFMPEGPacketConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::depthai_ros_msgs::FFMPEGPacket_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::depthai_ros_msgs::FFMPEGPacket_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::depthai_ros_msgs::FFMPEGPacket_<ContainerAllocator1> & lhs, const ::depthai_ros_msgs::FFMPEGPacket_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.width == rhs.width &&
    lhs.height == rhs.height &&
    lhs.encoding == rhs.encoding &&
    lhs.pts == rhs.pts &&
    lhs.flags == rhs.flags &&
    lhs.is_bigendian == rhs.is_bigendian &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::depthai_ros_msgs::FFMPEGPacket_<ContainerAllocator1> & lhs, const ::depthai_ros_msgs::FFMPEGPacket_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace depthai_ros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::depthai_ros_msgs::FFMPEGPacket_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::depthai_ros_msgs::FFMPEGPacket_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::depthai_ros_msgs::FFMPEGPacket_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::depthai_ros_msgs::FFMPEGPacket_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::depthai_ros_msgs::FFMPEGPacket_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::depthai_ros_msgs::FFMPEGPacket_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::depthai_ros_msgs::FFMPEGPacket_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4c1b25efca82fe4dd7addd520d7cc4b9";
  }

  static const char* value(const ::depthai_ros_msgs::FFMPEGPacket_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4c1b25efca82fe4dULL;
  static const uint64_t static_value2 = 0xd7addd520d7cc4b9ULL;
};

template<class ContainerAllocator>
struct DataType< ::depthai_ros_msgs::FFMPEGPacket_<ContainerAllocator> >
{
  static const char* value()
  {
    return "depthai_ros_msgs/FFMPEGPacket";
  }

  static const char* value(const ::depthai_ros_msgs::FFMPEGPacket_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::depthai_ros_msgs::FFMPEGPacket_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"int32 width       # original image width\n"
"int32 height      # original image height\n"
"string encoding	  # encoding used\n"
"uint64 pts        # packet pts\n"
"uint8  flags      # packet flags\n"
"bool is_bigendian # true if machine stores in big endian format\n"
"uint8[] data      # ffmpeg compressed payload\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::depthai_ros_msgs::FFMPEGPacket_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::depthai_ros_msgs::FFMPEGPacket_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.width);
      stream.next(m.height);
      stream.next(m.encoding);
      stream.next(m.pts);
      stream.next(m.flags);
      stream.next(m.is_bigendian);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FFMPEGPacket_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::depthai_ros_msgs::FFMPEGPacket_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::depthai_ros_msgs::FFMPEGPacket_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "width: ";
    Printer<int32_t>::stream(s, indent + "  ", v.width);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "height: ";
    Printer<int32_t>::stream(s, indent + "  ", v.height);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "encoding: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.encoding);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pts: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.pts);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "flags: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.flags);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "is_bigendian: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_bigendian);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "data: ";
    if (v.data.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint8_t>::stream(s, true ? std::string() : indent + "    ", v.data[i]);
    }
    if (v.data.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEPTHAI_ROS_MSGS_MESSAGE_FFMPEGPACKET_H
