// Generated by gencpp from file depthai_ros_msgs/TrackDetection2DArray.msg
// DO NOT EDIT!


#ifndef DEPTHAI_ROS_MSGS_MESSAGE_TRACKDETECTION2DARRAY_H
#define DEPTHAI_ROS_MSGS_MESSAGE_TRACKDETECTION2DARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <depthai_ros_msgs/TrackDetection2D.h>

namespace depthai_ros_msgs
{
template <class ContainerAllocator>
struct TrackDetection2DArray_
{
  typedef TrackDetection2DArray_<ContainerAllocator> Type;

  TrackDetection2DArray_()
    : header()
    , detections()  {
    }
  TrackDetection2DArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , detections(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::depthai_ros_msgs::TrackDetection2D_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::depthai_ros_msgs::TrackDetection2D_<ContainerAllocator> >> _detections_type;
  _detections_type detections;





  typedef boost::shared_ptr< ::depthai_ros_msgs::TrackDetection2DArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::depthai_ros_msgs::TrackDetection2DArray_<ContainerAllocator> const> ConstPtr;

}; // struct TrackDetection2DArray_

typedef ::depthai_ros_msgs::TrackDetection2DArray_<std::allocator<void> > TrackDetection2DArray;

typedef boost::shared_ptr< ::depthai_ros_msgs::TrackDetection2DArray > TrackDetection2DArrayPtr;
typedef boost::shared_ptr< ::depthai_ros_msgs::TrackDetection2DArray const> TrackDetection2DArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::depthai_ros_msgs::TrackDetection2DArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::depthai_ros_msgs::TrackDetection2DArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::depthai_ros_msgs::TrackDetection2DArray_<ContainerAllocator1> & lhs, const ::depthai_ros_msgs::TrackDetection2DArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.detections == rhs.detections;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::depthai_ros_msgs::TrackDetection2DArray_<ContainerAllocator1> & lhs, const ::depthai_ros_msgs::TrackDetection2DArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace depthai_ros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::depthai_ros_msgs::TrackDetection2DArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::depthai_ros_msgs::TrackDetection2DArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::depthai_ros_msgs::TrackDetection2DArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::depthai_ros_msgs::TrackDetection2DArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::depthai_ros_msgs::TrackDetection2DArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::depthai_ros_msgs::TrackDetection2DArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::depthai_ros_msgs::TrackDetection2DArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "028a359b954c2bd278a0618e859ff0f7";
  }

  static const char* value(const ::depthai_ros_msgs::TrackDetection2DArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x028a359b954c2bd2ULL;
  static const uint64_t static_value2 = 0x78a0618e859ff0f7ULL;
};

template<class ContainerAllocator>
struct DataType< ::depthai_ros_msgs::TrackDetection2DArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "depthai_ros_msgs/TrackDetection2DArray";
  }

  static const char* value(const ::depthai_ros_msgs::TrackDetection2DArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::depthai_ros_msgs::TrackDetection2DArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# A list of 2D tracklets, for a multi-object 2D tracker.\n"
"\n"
"std_msgs/Header header\n"
"# A list of the tracking proposals.\n"
"TrackDetection2D[] detections\n"
"\n"
"## These messages are created as close as possible to the official vision_msgs(http://wiki.ros.org/vision_msgs)\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: depthai_ros_msgs/TrackDetection2D\n"
"\n"
"# Class probabilities\n"
"vision_msgs/ObjectHypothesisWithPose[] results\n"
"\n"
"# 2D bounding box surrounding the object.\n"
"vision_msgs/BoundingBox2D bbox\n"
"\n"
"# If true, this message contains object tracking information.\n"
"bool is_tracking\n"
"\n"
"# ID used for consistency across multiple detection messages. This value will\n"
"# likely differ from the id field set in each individual ObjectHypothesis.\n"
"# If you set this field, be sure to also set is_tracking to True.\n"
"string tracking_id\n"
"\n"
"# Age: number of frames the object is being tracked\n"
"int32 tracking_age\n"
"\n"
"# Status of the tracking:\n"
"# 0 = NEW -> the object is newly added.\n"
"# 1 = TRACKED -> the object is being tracked.\n"
"# 2 = LOST -> the object gets lost now. The object can be tracked again automatically (long term tracking) \n"
"#			  or by specifying detected object manually (short term and zero term tracking).\n"
"# 3 = REMOVED -> the object is removed.\n"
"int32 tracking_status\n"
"\n"
"================================================================================\n"
"MSG: vision_msgs/ObjectHypothesisWithPose\n"
"# An object hypothesis that contains position information.\n"
"\n"
"# The unique numeric ID of object detected. To get additional information about\n"
"#   this ID, such as its human-readable name, listeners should perform a lookup\n"
"#   in a metadata database. See vision_msgs/VisionInfo.msg for more detail.\n"
"int64 id\n"
"\n"
"# The probability or confidence value of the detected object. By convention,\n"
"#   this value should lie in the range [0-1].\n"
"float64 score\n"
"\n"
"# The 6D pose of the object hypothesis. This pose should be\n"
"#   defined as the pose of some fixed reference point on the object, such a\n"
"#   the geometric center of the bounding box or the center of mass of the\n"
"#   object.\n"
"# Note that this pose is not stamped; frame information can be defined by\n"
"#   parent messages.\n"
"# Also note that different classes predicted for the same input data may have\n"
"#   different predicted 6D poses.\n"
"geometry_msgs/PoseWithCovariance pose\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseWithCovariance\n"
"# This represents a pose in free space with uncertainty.\n"
"\n"
"Pose pose\n"
"\n"
"# Row-major representation of the 6x6 covariance matrix\n"
"# The orientation parameters use a fixed-axis representation.\n"
"# In order, the parameters are:\n"
"# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n"
"float64[36] covariance\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: vision_msgs/BoundingBox2D\n"
"# A 2D bounding box that can be rotated about its center.\n"
"# All dimensions are in pixels, but represented using floating-point\n"
"#   values to allow sub-pixel precision. If an exact pixel crop is required\n"
"#   for a rotated bounding box, it can be calculated using Bresenham's line\n"
"#   algorithm.\n"
"\n"
"# The 2D position (in pixels) and orientation of the bounding box center.\n"
"geometry_msgs/Pose2D center\n"
"\n"
"# The size (in pixels) of the bounding box surrounding the object relative\n"
"#   to the pose of its center.\n"
"float64 size_x\n"
"float64 size_y\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose2D\n"
"# Deprecated\n"
"# Please use the full 3D pose.\n"
"\n"
"# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n"
"\n"
"# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n"
"\n"
"\n"
"# This expresses a position and orientation on a 2D manifold.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 theta\n"
;
  }

  static const char* value(const ::depthai_ros_msgs::TrackDetection2DArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::depthai_ros_msgs::TrackDetection2DArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.detections);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TrackDetection2DArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::depthai_ros_msgs::TrackDetection2DArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::depthai_ros_msgs::TrackDetection2DArray_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "detections: ";
    if (v.detections.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.detections.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::depthai_ros_msgs::TrackDetection2D_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.detections[i]);
    }
    if (v.detections.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEPTHAI_ROS_MSGS_MESSAGE_TRACKDETECTION2DARRAY_H
