<?xml version="1.0"?>

<package format="2">

  <!-- ====================================================== -->
  <!-- Package Information                                    -->
  <!-- ====================================================== -->

  <name>spar_node</name>

  <version>0.0.0</version>

  <description>
    SPAR flight-control interface and EGH450 autonomous
    guidance / navigation mission controller.
  </description>


  <!-- ====================================================== -->
  <!-- Maintainer / Licence                                   -->
  <!-- ====================================================== -->

  <maintainer email="pryre@todo.todo">
    pryre
  </maintainer>

  <license>TODO</license>


  <!-- ====================================================== -->
  <!-- Build System                                           -->
  <!-- ====================================================== -->

  <buildtool_depend>
    catkin
  </buildtool_depend>


  <!-- ====================================================== -->
  <!-- Build Dependencies                                     -->
  <!-- ====================================================== -->

  <build_depend>
    actionlib
  </build_depend>

  <build_depend>
    actionlib_msgs
  </build_depend>

  <build_depend>
    geometry_msgs
  </build_depend>

  <build_depend>
    mavros_msgs
  </build_depend>

  <build_depend>
    roscpp
  </build_depend>

  <build_depend>
    rospy
  </build_depend>

  <build_depend>
    sensor_msgs
  </build_depend>

  <build_depend>
    spar_msgs
  </build_depend>

  <build_depend>
    std_msgs
  </build_depend>


  <!-- ====================================================== -->
  <!-- Build Export Dependencies                              -->
  <!-- ====================================================== -->

  <build_export_depend>
    actionlib
  </build_export_depend>

  <build_export_depend>
    actionlib_msgs
  </build_export_depend>

  <build_export_depend>
    geometry_msgs
  </build_export_depend>

  <build_export_depend>
    mavros_msgs
  </build_export_depend>

  <build_export_depend>
    roscpp
  </build_export_depend>

  <build_export_depend>
    rospy
  </build_export_depend>

  <build_export_depend>
    sensor_msgs
  </build_export_depend>

  <build_export_depend>
    spar_msgs
  </build_export_depend>

  <build_export_depend>
    std_msgs
  </build_export_depend>


  <!-- ====================================================== -->
  <!-- Runtime Dependencies                                   -->
  <!-- ====================================================== -->

  <exec_depend>
    actionlib
  </exec_depend>

  <exec_depend>
    actionlib_msgs
  </exec_depend>

  <exec_depend>
    geometry_msgs
  </exec_depend>

  <exec_depend>
    mavros_msgs
  </exec_depend>

  <exec_depend>
    roscpp
  </exec_depend>

  <exec_depend>
    rospy
  </exec_depend>

  <exec_depend>
    sensor_msgs
  </exec_depend>

  <exec_depend>
    spar_msgs
  </exec_depend>

  <exec_depend>
    std_msgs
  </exec_depend>


  <!-- ====================================================== -->
  <!-- Package Export                                         -->
  <!-- ====================================================== -->

  <export>
  </export>

</package>